# Generated by Django 5.2.7 on 2025-11-05 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(default='LENTES-001', max_length=50, unique=True)),
                ('nombre', models.CharField(default='Lentes Sensoriales', max_length=100)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='INACTIVO', max_length=20)),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F'), ('O', 'O')], max_length=10)),
                ('notas', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SesionPaciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('cuidador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cuidador')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dispositivo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='MensajeCuidador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=128)),
                ('leido', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cuidador')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sesionpaciente')),
            ],
        ),
        migrations.CreateModel(
            name='DatoSensor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=20)),
                ('temperatura', models.FloatField()),
                ('distancia', models.FloatField()),
                ('nivel', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sesionpaciente')),
            ],
        ),
        migrations.CreateModel(
            name='ComandoControl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comando', models.CharField(max_length=50)),
                ('parametros', models.CharField(blank=True, max_length=100)),
                ('ejecutado', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sesionpaciente')),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('mensaje', models.CharField(max_length=100)),
                ('severidad', models.CharField(default='MEDIA', max_length=10)),
                ('vista', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sesionpaciente')),
            ],
        ),
    ]
